/*
 * This file was last modified at 2024-04-20 17:09 by Victor N. Skurikhin.
 * accrual_easyjson.go
 * $Id$
 */

// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB608c935DecodeGithubComVskurikhinGophermartInternalModel(in *jlexer.Lexer, out *Accrual) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.Order = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "accrual":
			out.Accrual = Float(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB608c935EncodeGithubComVskurikhinGophermartInternalModel(out *jwriter.Writer, in Accrual) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.Order))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"accrual\":"
		out.RawString(prefix)
		(in.Accrual).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Accrual) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB608c935EncodeGithubComVskurikhinGophermartInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Accrual) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB608c935EncodeGithubComVskurikhinGophermartInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Accrual) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB608c935DecodeGithubComVskurikhinGophermartInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Accrual) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB608c935DecodeGithubComVskurikhinGophermartInternalModel(l, v)
}
