/*
 * This file was last modified at 2024-04-19 16:34 by Victor N. Skurikhin.
 * balance_easyjson.go
 * $Id$
 */

// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBed2650eDecodeGithubComVskurikhinGophermartInternalModel(in *jlexer.Lexer, out *Balance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "current":
			out.Current = Float(in.Float64())
		case "withdrawn":
			out.Withdrawn = Float(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBed2650eEncodeGithubComVskurikhinGophermartInternalModel(out *jwriter.Writer, in Balance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"current\":"
		out.RawString(prefix[1:])
		(in.Current).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"withdrawn\":"
		out.RawString(prefix)
		(in.Withdrawn).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (b Balance) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBed2650eEncodeGithubComVskurikhinGophermartInternalModel(&w, b)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (b Balance) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBed2650eEncodeGithubComVskurikhinGophermartInternalModel(w, b)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (b *Balance) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBed2650eDecodeGithubComVskurikhinGophermartInternalModel(&r, b)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (b *Balance) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBed2650eDecodeGithubComVskurikhinGophermartInternalModel(l, b)
}
