/*
 * This file was last modified at 2024-04-20 17:09 by Victor N. Skurikhin.
 * withdraw_easyjson.go
 * $Id$
 */

// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4f4a6fc6DecodeGithubComVskurikhinGophermartInternalModel(in *jlexer.Lexer, out *Withdraw) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.Order = string(in.String())
		case "sum":
			(out.Sum).UnmarshalEasyJSON(in)
		case "processed_at":
			if in.IsNull() {
				in.Skip()
				out.ProcessedAt = nil
			} else {
				if out.ProcessedAt == nil {
					out.ProcessedAt = new(Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.ProcessedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f4a6fc6EncodeGithubComVskurikhinGophermartInternalModel(out *jwriter.Writer, in Withdraw) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.Order))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		(in.Sum).MarshalEasyJSON(out)
	}
	if in.ProcessedAt != nil {
		const prefix string = ",\"processed_at\":"
		out.RawString(prefix)
		(*in.ProcessedAt).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Withdraw) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4f4a6fc6EncodeGithubComVskurikhinGophermartInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Withdraw) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4f4a6fc6EncodeGithubComVskurikhinGophermartInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Withdraw) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4f4a6fc6DecodeGithubComVskurikhinGophermartInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Withdraw) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4f4a6fc6DecodeGithubComVskurikhinGophermartInternalModel(l, v)
}
